### ISSUE TITLE
Foreach in a condition?

### ISSUE THREAD

**Issue by soifou** [owebia/magento1-module-advanced-shipping#11]
It's not an issue but I don't know if the condition I'm trying to do is possible.

I want to browse some of my cart items with a particular attribute and check if these matched products doesn't exceed a value.

This could be translated by the following condition :

```
"conditions": "
        {foreach cart.items where product.attribute.category_offer == 10}
            {product.attribute.colis_length.value}<=200
        {/foreach}
"
```

The `sum` or `count`have the capability to iterate over cart items by filtering on a particular attribute but this would be nice if we can use `foreach` to do the same.

Is there any other way to achieve my case?
Thanks in advance.

**Comment by owebia** [comment]
Why do you want to use foreach when you can combine conditions:

```
"conditions": "{count items where product.attribute.category_offer == 10 && product.attribute.colis_length.value > 200} == 0"
```

**Comment by soifou** [comment]
Indeed, seen from this perspective, foreach is useless. I think I did too much attempts to find the right condition that I lost myself. Thanks !
