### ISSUE TITLE
Cannot declare class PhpParser\Autoloader

### ISSUE THREAD

**Issue by paugnu** [owebia/magento1-module-advanced-shipping#13]
Hi,

After installing the module in a Magento 1.9.3.1 (with all the patches included) I'm having the following error when I try to flush cache using n98-magerun.phar cache:clean // cache:flush :
PHP Fatal error:  Cannot declare class PhpParser\Autoloader, because the name is already in use in /var/www/brildor.lxc/src/lib/PhpParser/Autoloader.php on line 8

I'm not sure why this is happening:
* Compiler is not enabled
* I've emptied var/cache, /tmp, flushed cache from backoffice, flushed redis cache, disabled redis...
* Removed everything and check that everything works fine without the owebia module

Any idea why this is happening?

**Comment by owebia** [comment]
Hi @PauGNU, thanks for your feedback.

The package nikic\php-parser is included in n98-magerun.phar  
It creates a conflict with the class loaded by Advanced Shipping module.

I will try to add a fix in next release.

Best Regards,  
A.L.

**Comment by owebia** [comment]
@PauGNU you can use the following code to fix the issue before the next release:

`if (!class_exists('\PhpParser\Autoloader', false)) {`

Best Regards,  
A.L.

**Comment by paugnu** [comment]
Thank @owebia , this fix seems to work correctly (I added it to the Observer.php file):

`if (!static::$registered && !class_exists('\PhpParser\Autoloader', false)) {`
