### ISSUE TITLE
coupon_code not working / coupon_code ne fonctionne pas 

### ISSUE THREAD

**Issue by AnthonyIp** [owebia/magento1-module-advanced-shipping#15]
Hi , 

I'm using the latest version of Magento 1.9.
I have an issue where we set a coupon code that gives free shipping with it.
```
   "test": {
      "label": "Coupon livraison gratuite",
      "shipto": "FR-(2A,2B)",
      "conditions": "{cart.coupon_code}=='FREESHIPPING'",
      "fees": 0
   },
```   
From code, this goes to _evalFormula() which return a **null** 
 
How does the coupon_code works ? Is my setting from the shipping method wrong ? 

Thanks

---------------------------------------------------------------

Bonjour,

J'utilise la derniere version de magento 1.9.
Je rencontre actuellement un soucis sur les code promo ou je souhaite donner une livraison gratuite.
Voici ma config:
```
   "test": {
      "label": "Coupon livraison gratuite",
      "shipto": "FR-(2A,2B)",
      "conditions": "{cart.coupon_code}=='FREESHIPPING'",
      "fees": 0
   },
```   

Du point de vue code, je vois que cela va dans _evalFormula() qui retourne un **null**

Comment les code promo fonctionne elle ? est ce ma configuration qui n'est pas bonne ?

Merci

**Comment by HugRap** [comment]
Hi Anthony, you need to use double brackets like this:

"test": {
      "label": "Coupoun livraison gratuite",
      "shipto": "FR-(2A,2B)",
      "conditions": "**{**{cart.coupon_code}**}**=='FREESHIPPING'",
      "fees": 0
   },

See documentation here: https://owebia.com/doc/fr/magento1-module-advanced-shipping#examples_using_formulas

**Comment by AnthonyIp** [comment]
It still doesn't work 
The double bracket doesn't work
When I tried to apply it, I have the alert "Coupon code "FREESHIPPING" is not valid."

Here are my shopping cart rule settings

Rule information:
- Rule name : Free shipping
- Status :  active
- website : Main Website
- Customer Groups: **All Selected**
- Coupon : Specific Coupon
- Coupon Code : FREESHIPPING
- Uses per coupon: 1000
- Uses Per Customer: 1000
- From Date: 14/09/2021
- To Date : 31/12/2025
- Priority: 0
- Public RSS feed: No

Conditions:
- If all of these conditions are TRUE
    - Subtotal equals or greater than 0
    
Thanks

**Comment by owebia** [comment]
Hi @AnthonyIp,

As @HugRap said, you should use double curly braces to auto-escape the coupon code, then the formula evaluation will not fail.

Your second error is not thrown by Owebia Advanced Shipping but by Magento.
Our module does not change how the coupon codes are handled by Magento.

With what you show, I don't see an obvious error in the coupon code configuration but there is probably an issue with your coupon code.

Here are some similar problems:
- https://community.magento.com/t5/Magento-2-x-Admin-Configuration/Percentage-Discount-code-Code-not-Valid-Error/td-p/402193
- https://community.magento.com/t5/Installing-Magento-1-x/RESOLVED-All-Coupon-codes-have-stopped-working-quot-coupon-code/td-p/5059

I hope it will help you.

Best Regards,
A.L.

**Comment by AnthonyIp** [comment]
Hi @owebia ! 

For some reason, double curl doesn't fix the issue.

However, I fixed the second error for "Coupon XXX is not valid" which the cause was the expiration date was too far away.

**Comment by owebia** [comment]
If you still have an issue, you can enable the debug option and then make a shipping estimation to see how the formula is evaluated.
It may give you some clues about your issue.

Best Regards,
A.L.
