### ISSUE TITLE
parseSize error 'A non well formed numeric value encountered'

### ISSUE THREAD

**Issue by rphilippe** [owebia/magento1-module-advanced-shipping#7]
Hello,

I'm using PHP 7.1.0 and I get the following error in the `parseSize` function from the `ConfigParser.php` : 

> A non well formed numeric value encountered.

It's possible to rewrite `ConfigParser.php` but it's a pain because `static::` is used several times...

There is a PR : #5 with a solution (there are several ways to fix it but this one is working), is there any ETA for a merge?

Thank you.

**Comment by owebia** [comment]
Fixed by merging the PR https://github.com/owebia/magento1-module-shipping-free/pull/5

Thanks
